name = "Minecraft Server Pack"
author = "nikitays0987"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "910d8c5f52f29d06f06c793be2b5098365e93051ce343b54fbc1af8321971f4d"

[versions]
forge = "65.1.0"
minecraft = "26.2"
