name = "Minecraft Server Pack"
author = "nikitays0987"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42126415e0f3892a7e727348dabd360dc232184fb4ef523bca9b1b55af6f9498"

[versions]
forge = "65.1.0"
minecraft = "26.2"
