name = "Minecraft Server Pack"
author = "nikitays0987"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28662b544f7dfba7a86fbe191173d225c46c276cc142c1a5bac738a188f10c4a"

[versions]
forge = "65.1.0"
minecraft = "26.2"
